services:
  pgadmin4:
    image: dpage/pgadmin4:latest
    pull_policy: always
    restart: always
    env_file: .env
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin4/pgpass:/pgpass:ro
    depends_on:
      postgresql:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
