FROM postgres:10

ENV POSTGRES_USER dhis
ENV POSTGRES_PASSWORD dhis
ENV POSTGRES_DB dhis

COPY wait-for-it.sh *.sql /dhis2/
RUN mkdir -p /dhis2

RUN apt-get update \
    && apt-get install -y postgresql-10-postgis-2.4 curl \
    && rm -rf /var/lib/apt/lists/*
