version: '3.1'

services: 
  dhis2mq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  dhis2db:
    image: dhis2db:latest
    build: 
      context: .
      dockerfile: ./Dockerfile-db
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
  dhis2tc:
    image: dhis2tc:latest
    build: 
      context: .
      dockerfile: ./Dockerfile-tc
    depends_on: 
      - dhis2db
      - dhis2mq
    ports:
      - 8080:8080
    entrypoint: /dhis2/wait-for-it.sh -t 50000 dhis2mq:5672 -- /dhis2/wait-for-it.sh -t 50000 dhis2db:5432 --
    command: catalina.sh run
    restart: always
